### ISSUE TITLE
" Could not execute entrypoint stage 'main' due to errors, provided by 'patchwork-dispatcher'! " error when trying to use Music Player mod.

### ISSUE THREAD

**Issue by MrPotatoMan-Jackaboy** [PatchworkMC/patchwork-api#136]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'patchwork-dispatcher'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.method_1503(class_310.java)
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	Suppressed: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
		at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
		at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.fabric.api.event.server.ServerStartCallback.lambda$static$1(ServerStartCallback.java:31)
		at net.fabricmc.fabric.api.event.server.ServerStartCallback$$Lambda$1433/1256061845.apply(Unknown Source)
		at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:44)
		at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:35)
		at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:46)
		at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:42)
		at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:57)
		at net.fabricmc.fabric.api.event.server.ServerStartCallback.<clinit>(ServerStartCallback.java:30)
		at net.patchworkmc.impl.event.lifecycle.LifecycleEvents.onInitialize(LifecycleEvents.java:100)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1380/49199879.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 12 more
	Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector proxyPutWorld(Ljava/util/Map;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in patchwork-events-world.mixins.json:MixinMinecraftServer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap patchwork-events-world-refmap.json
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
		... 29 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.fabricmc.fabric.api.event.server.ServerStartCallback
		at net.patchworkmc.impl.fml.PatchworkFML.onInitialize(PatchworkFML.java:37)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1380/49199879.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 12 more
	Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.fabricmc.fabric.api.event.server.ServerStartCallback
		at net.patchworkmc.impl.biomes.PatchworkBiomes.onInitialize(PatchworkBiomes.java:46)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1380/49199879.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 12 more
	Suppressed: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
		at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
		at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
		at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$1(ServerLifecycleEvents.java:35)
		at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents$$Lambda$1449/1171086422.apply(Unknown Source)
		at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.update(ArrayBackedEvent.java:44)
		at net.fabricmc.fabric.impl.base.event.ArrayBackedEvent.<init>(ArrayBackedEvent.java:35)
		at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:46)
		at net.fabricmc.fabric.impl.base.event.EventFactoryImpl.createArrayBacked(EventFactoryImpl.java:42)
		at net.fabricmc.fabric.api.event.EventFactory.createArrayBacked(EventFactory.java:57)
		at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.<clinit>(ServerLifecycleEvents.java:35)
		at net.fabricmc.fabric.impl.event.lifecycle.LegacyEventInvokers.onInitialize(LegacyEventInvokers.java:31)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1380/49199879.accept(Unknown Source)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
		... 12 more
	Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector proxyPutWorld(Ljava/util/Map;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in patchwork-events-world.mixins.json:MixinMinecraftServer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap patchwork-events-world-refmap.json
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
		... 29 more
Caused by: net.patchworkmc.impl.PatchworkInitializationException: Failed to construct Patchwork mods
	at net.patchworkmc.impl.Patchwork.onInitialize(Patchwork.java:107)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient$$Lambda$1380/49199879.accept(Unknown Source)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 12 more
	Suppressed: java.lang.NoSuchMethodError: net.minecraftforge.fml.loading.moddiscovery.ModFile.findResource(Ljava/lang/String;)Ljava/nio/file/Path;
		at info.u_team.music_player.dependency.DependencyManager.findJarFilesInJar(DependencyManager.java:53)
		at info.u_team.music_player.dependency.DependencyManager.construct(DependencyManager.java:32)
		at info.u_team.music_player.proxy.ClientProxy.construct(ClientProxy.java:24)
		at info.u_team.music_player.MusicPlayerMod.<init>(MusicPlayerMod.java:20)
		at patchwork_generated.info.u_team.music_player.MusicPlayerModInitializer.constructTargetMod(Unknown Source)
		at patchwork_generated.info.u_team.music_player.MusicPlayerModInitializer.onForgeInitialize(Unknown Source)
		at net.patchworkmc.impl.Patchwork.onInitialize(Patchwork.java:104)
		... 14 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.method_1503(class_310.java)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.class_310.method_1514(class_310.java:394)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 787010736 bytes (750 MB) / 1140850688 bytes (1088 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 2
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		fabric: Fabric API 0.15.0+build.259-1.14
		fabric-api-base: Fabric API Base 0.1.2+28f8190f42
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.1+28f8190f42
		fabric-command-api-v1: Fabric Command API (v1) 1.0.1+b534aa0c42
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+bfd4c99d42
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+28f8190f42
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.2+28f8190f42
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+28f8190f42
		fabric-dimensions-v1: fabric-dimensions-v1 0.1.1+e15ff88642
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+6e76156542
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+c6bdeeaa42
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+c6bdeeaa42
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+7ce6c57742
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+9e24fbc342
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+85811ffb42
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.1.0+f27aa19d42
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.1+28f8190f42
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+28f8190f42
		fabric-models-v0: Fabric Models (v0) 0.1.0+933c24c242
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.1+28f8190f42
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e7757afe42
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.0.0+002fcb6542
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.2.0+002fcb6542
		fabric-particles-v1: fabric-particles-v1 0.2.1+e9056b2242
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.3+28f8190f42
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.1.1+933c24c242
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.1.14+e15ff88642
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.2+28f8190f42
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.3+28f8190f42
		fabric-rendering-v0: Fabric Rendering (v0) 0.1.2+28f8190f42
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.4+28f8190f42
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+d423005742
		fabric-textures-v0: Fabric Textures (v0) 0.1.4+933c24c242
		fabricloader: Fabric Loader 0.8.9+build.203
		minecraft: Minecraft 1.14.4
		musicplayer: Music Player ${file.jarVersion}
		patchwork: Patchwork 0.7.0
		patchwork-biomes: Patchwork Biomes 0.2.0+e18acfc8
		patchwork-capabilities: Patchwork Capabilities support 0.2.0+e18acfc8
		patchwork-data-generators: Patchwork Data Generators 0.2.0+e18acfc8
		patchwork-dispatcher: Patchwork Dispatcher 0.3.0+827b7347
		patchwork-enum-hacks: Patchwork Enum Hacks 0.2.0+e18acfc8
		patchwork-eventbus: Patchwork EventBus 0.2.0
		patchwork-events-entity: Patchwork Entity Events 0.4.0+929bf8d0
		patchwork-events-input: Patchwork Input Events 0.2.0+e18acfc8
		patchwork-events-lifecycle: Patchwork Lifecycle Events 0.2.0+e18acfc8
		patchwork-events-rendering: Patchwork Rendering Events 0.2.0+e18acfc8
		patchwork-events-world: Patchwork World Events 0.2.0+e18acfc8
		patchwork-extensions: Patchwork Extensions 0.2.0+e18acfc8
		patchwork-extensions-block: Patchwork Extensions Block 0.2.0+e18acfc8
		patchwork-extensions-item: Patchwork Item Extensions 0.2.0+e18acfc8
		patchwork-extensions-shearing: Patchwork Extensions Shearing 0.2.0+e18acfc8
		patchwork-fml: Patchwork FML Interface 0.2.0+e18acfc8
		patchwork-gui: Patchwork GUI 0.2.0+e18acfc8
		patchwork-level-generators: Patchwork Level Generators 0.2.0+e18acfc8
		patchwork-loot: Patchwork Loot 0.2.0+e18acfc8
		patchwork-networking: Patchwork Networking 0.2.0+e18acfc8
		patchwork-networking-messages: Patchwork Networking Messages 0.2.0+e18acfc8
		patchwork-recipes: Patchwork Recipes 0.2.0+e18acfc8
		patchwork-registries: Patchwork Registries 0.3.0+827b7347
		patchwork-tooltype: Patchwork ToolType 0.2.0+e18acfc8
		patchwork-vanilla-patches: Patchwork Vanilla Patches 0.2.0+e18acfc8
		uteamcore: U Team Core ${file.jarVersion}
	Launched Version: fabric-loader-0.8.9+build.203-1.14.4
	LWJGL: 3.2.2 build 10
	OpenGL: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: ~~ERROR~~ NullPointerException: null
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: <unknown>

**Comment by rikka0w0** [comment]
`net.minecraftforge.fml.loading.moddiscovery.ModFile.findResource(Ljava/lang/String;)Ljava/nio/file/Path;` is not implemented. It requires ModInfo stuff, which is complicated and not well understood. If possible, you can have a look at the source code of the mod that you are trying to run. `info.u_team.music_player.dependency.DependencyManager.findJarFilesInJar` seems like a dependency check, remove this call and replace it with some dummy function may make it work.
